apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  namespace: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: voting-app
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: vote
spec:
  selector:
    app: voting-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort

